source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.2'

gem 'rails', '~> 5.2.0'
gem 'sqlite3'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'active_model_serializers', '~> 0.10.7'
gem 'jbuilder', '~> 2.7'
gem 'rack-cors', '~> 1.0', '>= 1.0.2'
gem 'rack-attack', '~> 5.2'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'knock', '~> 2.1', '>= 2.1.1'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'mini_magick', '~> 4.8'
gem 'paperclip', '~> 6.0'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'faker'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :test do
  gem 'factory_bot_rails', '~> 4.10'
  gem 'rspec-rails', '~> 3.7', '>= 3.7.2'
  gem 'database_cleaner', '~> 1.7'
  gem 'shoulda-matchers', '~> 3.1', '>= 3.1.2'
  gem 'simplecov', require: false
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'spring-commands-rspec', '~> 1.0', '>= 1.0.4'
  gem 'foreman', '~> 0.82.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
